name: Run Tests & Upload Coverage

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  build_test_upload_coverage:
    runs-on: [windows-latest]

    defaults:
      run:
        shell: msys2 {0}
    env:
      CXX: g++
      CC: gcc
      CMAKE_CXX_COMPILER: g++
      CMAKE_C_COMPILER: gcc
      CMAKE_GENERATOR: MSYS Makefiles

    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ucrt64
          update: true
          install: >-
            lcov
            cmake
            make
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p

      - name: Configure CMake for Debug and Code Coverage
        # Configure CMake with the DEBUG build type and code coverage enabled
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON

      - name: Build
        # Build your program
        run: cmake --build ${{github.workspace}}/build --config Debug
      
      - name: Test
        # Run tests
        run: ctest --test-dir ${{github.workspace}}/build --output-on-failure

      - name: Log Info
        run: tree

      - name: Collect Coverage
        # Run tests and generate coverage report
        run: cmake --build ${{github.workspace}}/build --target coverage

      - name: Find and Upload Coverage
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{github.workspace}}/build/coverage.info
