name: CMake

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: [windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        # Configure CMake with the DEBUG build type and code coverage enabled
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON

      - name: Build
        # Build your program
        run: cmake --build ${{github.workspace}}/build --config Debug

      - name: Test
        # Run tests
        run: ctest --test-dir ${{github.workspace}}/build --output-on-failure

      - name: Find and Upload Coverage
        # Find and upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
