name: CMake

on:
  push:
    branches: ["main", "dev-WIP"]
  pull_request:
    branches: ["main", "dev-WIP"]

jobs:
  build:
    runs-on: [windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: |
            ${{github.workspace}}/vcpkg
            ${{github.workspace}}/static_site/node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/package-lock.json', '**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-

      - name: Configure CMake
        # Configure CMake with the DEBUG build type and code coverage enabled
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON

      - name: Build
        # Build your program
        run: cmake --build ${{github.workspace}}/build --config Debug

      - name: Test
        # Run tests
        run: ctest --test-dir ${{github.workspace}}/build --output-on-failure

      - name: Generate Coverage
        run: |
          choco install opencppcoverage
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH
          refreshenv
          OpenCppCoverage.exe --excluded_sources ${{github.workspace}}\static_site --export_type cobertura:${{github.workspace}}\Coverage.xml -- ${{github.workspace}}\build\bin\LoginLanguish_tests

      - name: Find and Upload Coverage
        # Find and upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
